- name: Build and push docker image project
  hosts: "{{ build_and_push_docker_image_playbook_host }}"
  become: yes

  vars_files:
    - /root/wallet_project/ansible/playbook_vars/docker_vars.yml
    - /root/wallet_project/ansible/playbook_vars/retry_task_vars.yml

  tasks:
    - include_tasks: tasks/login_to_docker.yml

    - name: Remove
      community.docker.docker_image_remove:
        name: "{{ docker_username }}/{{ docker_image }}"
        tag: "{{ docker_image_tag }}"
      retries: "{{ retries_count }}"
      delay: "{{ delay_time }}"

    - name: Build
      community.docker.docker_image_build:
        name: "{{ docker_username }}/{{ docker_image }}"
        tag: "{{ docker_image_tag }}"
        path: "{{ dockerfile_path }}"
        platform: "{{ docker_image_platform }}"
      retries: "{{ retries_count }}"
      delay: "{{ delay_time }}"

    - name: Push
      community.docker.docker_image_push:
        name: "{{ docker_username }}/{{ docker_image }}"
        tag: "{{ docker_image_tag }}"
      retries: "{{ retries_count }}"
      delay: "{{ delay_time }}"

    - include_tasks: tasks/docker_prune.yml
